name: wondesen_workshop
description: "A new Flutter project for Wondesen Workshop."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI and Fonts
  cupertino_icons: ^1.0.6
  google_fonts: ^8.2.1

  # Local Storage & Utilities
  shared_preferences: ^2.5.5

  # Media & Speech Packages
  video_player: ^2.8.2
  speech_to_text: ^7.4.0
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/icon.png